### ISSUE TITLE
Tạo file trong folder Repositories

### ISSUE THREAD

**Issue by Junn1o** [Junn1o/API#16]
Tạo các file IUserRepository và IAuthorRepository trong thư mục Repositories

**Comment by KENHUYNHIT** [comment]
Phần Repositories:  IUserRepository, IAuthorRepository, ICategoryRepository. Em đã làm xong  push lên rồi anh kiểm tra cho em nha.

**Comment by Junn1o** [comment]
là em push chưa vậy. Với lại anh kêu làm file IUserRepository và IAuthorRepository thôi mà..., lần sau nhìn đúng cái anh giao đừng có làm hết

**Comment by Junn1o** [comment]
> Phần Repositories: IUserRepository, IAuthorRepository, ICategoryRepository. Em đã làm xong push lên rồi anh kiểm tra cho em nha.



> là em push chưa vậy. Với lại anh kêu làm file IUserRepository và IAuthorRepository thôi mà..., lần sau nhìn đúng cái anh giao đừng có làm hết



> Phần Repositories: IUserRepository, IAuthorRepository, ICategoryRepository. Em đã làm xong push lên rồi anh kiểm tra cho em nha.

là em push chưa vậy. Với lại anh kêu làm file IUserRepository và IAuthorRepository thôi mà..., lần sau nhìn đúng cái anh giao đừng có làm hết
